services:
  # A web service for the FastAPI backend
  - type: web
    name: finance-app-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://finance-app-7a318.web.app,https://finance-app-7a318.firebaseapp.com
      - key: ENV
        value: production
      - key: DEBUG
        value: false
    # Secret files for secure credential storage
    secretFiles:
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        path: serviceAccountKey.json
    # Uncomment and configure if you need a database
    # databases:
    #   - name: finance-app-db
